### ISSUE TITLE
添加第三方库的问题

### ISSUE THREAD

**Issue by OnonokiYotsuki** [MeetWq/meme-generator-contrib#13]
萌新想问一下，改写配置文件后需要重启docker容器吗？
我重启之后发现配置文件被重置了，
不重启发请求提示not found

**Comment by MeetWq** [comment]
docker 的话不建议直接改配置文件，改这些预设的环境变量
https://github.com/MeetWq/meme-generator/blob/main/docs/docker.md

**Comment by OnonokiYotsuki** [comment]
> docker 的话不建议直接改配置文件，改这些预设的环境变量
> https://github.com/MeetWq/meme-generator/blob/main/docs/docker.md

谢谢 解决了:)
