### ISSUE TITLE
meme_generator.manager:load_meme:32 - Failed to import meme_generator.memes.do!

### ISSUE THREAD

**Issue by Felix-sec** [MeetWq/meme-generator-contrib#23]
我把额外表情"do"文件夹直接拷贝到D:\Program Files\Python38\Lib\site-packages\meme_generator\memes
随便运行个meme命令使它load一下，然后报错了，请问咋回事？
**Python版本：3.8.10
meme-generator版本：0.0.19.1
操作系统：win10**
![image](https://github.com/user-attachments/assets/c6adea66-57b1-4018-8784-10621baefe07)

**Comment by MeetWq** [comment]
你的python版本低了，本项目已不再支持python3.8

**Comment by Felix-sec** [comment]
> 你的python版本低了，本项目已不再支持python3.8

收到，非常感谢您！
